language: node_js
services:
  - mysql
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - mysql -e 'create database mysqlcache;'
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/* && node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info